version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:16.2-alpine
    restart: unless-stopped
    env_file:
      - .dev/.env.postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
